### ISSUE TITLE
код нечитаем

### ISSUE THREAD

**Issue by Er2ch** [DemetryF/evaluate-mathematic-expressions#1]
особенно парсер
прошу исправить

**Comment by DemetryF** [comment]
Смотрите ветку dev-3.0 (называется так на 22 марта 21 года), там уже есть отрефакторенный код. Спасибо.

**Comment by Er2ch** [comment]
Код стал читабельнее, но есть некоторые моменты:
1. Некоторые части кода ещё не переписаны (на то он и dev)
2. Складывать всё в заголовки - не очень хорошая идея, потому что предназначались они не для тела функций
3. Иногда, расположение всех файлов в одной директории (папке) лучше, чем отдельно
4. Зачем кастить (менять тип) при выделении памяти, ведь переменная автоматически конвертирует в этот же тип
5. \\ - плохой знак для деления нацело. Можно использовать // (комментарии будут не сишные), : или ещё что-то придумать

А так вроде нормально

**Comment by DemetryF** [comment]
1. Да, код еще не дописан, постараюсь свести к минимуму косяки.
2. Пока что будет так, может в следующей версии сделаю через систему сборки.
3. Да не, как по мне была бы куча, и фиг проссышь к чему относится find_divider_pos.h))
4. И тем не менее компилятор плюсов этого требует, даже к примитивам.
5. Все лексемы одинарные))
6. Ну это относится ко 2 пункту.

**Comment by Er2ch** [comment]
3. Как куда? Это же часть парсера
4. gcc и без этого спокойно компилирует. А насчёт плюсов, Вы собираетесь переписать калькулятор на C++?
5. Это к примеру было. А вообще, в лексере есть переменная last неиспользуемая, её можно использовать для лексинга той же //.

**Comment by DemetryF** [comment]
3. Ну тк он и находится в папке parser, а так была бы куча.
4. Не, я к примеру, типо Бьерн рекомендует приводить типы))
5. Она использовалась для проверки валидности выражения, что бы не было очевидно не правильных сочетаний токенов, например 2 десятичные точки подряд, и так далее, но потом перенес в отдельную функцию. А так, думаю и так сойдет, ведь в .help это можно узнать.

**Comment by Ddystopia** [comment]
Биба и Боба

**Comment by Er2ch** [comment]
3. Так её можно положить в parser.c
4. Ладно
5. Вообще, лексеры смотрят код во все стороны, но тут простой лексер, можно для целого деления использовать символ :

**Comment by DemetryF** [comment]
кстати да, но могу попробовать и сделать для 2 символов. Хотя думаю не принципиально

**Comment by DemetryF** [comment]
В любом случае - не хочется трогать старую версию, и оставить как есть. А в новый версиях буду уже решать. Учту эти моменты.

**Comment by Er2ch** [comment]
Решил часть моментов, автор может ориентироваться на это:  https://github.com/Er2ch/evaluate-mathematic-expressions/tree/dev-3.0

**Comment by DemetryF** [comment]
Спасибо) Ишшью можно закрывать? Или еще есть вопросы?
